#!/bin/bash

# @gf3’s Sexy Bash Prompt, inspired by “Extravagant Zsh Prompt”
# Shamelessly copied from Rob Chatfield, who copied from Paul Irish, who copied from this guy https://github.com/gf3/dotfiles

default_username='luke'

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

if tput setaf 1 &> /dev/null; then
    tput sgr0
    if [[ $(tput colors) -ge 256 ]] 2>/dev/null; then
        WHITE=$(tput setaf 256)
        GREEN=$(tput setaf 28)
        BLUE=$(tput setaf 25)
        RED=$(tput setaf 160)
    else
        WHITE=$(tput setaf 7)
        GREEN=$(tput setaf 2)
        BLUE=$(tput setaf 4)
        RED=$(tput setaf 1)
    fi
    BOLD=$(tput bold)
    RESET=$(tput sgr0)
else
    WHITE="\033[1;37m"
    GREEN="\033[1;32m"
    BLUE="\033[1;35m"
    RED="\033[1;33m"
    BOLD=""
    RESET="\033[m"
fi


function git_info() {
    # check if we're in a git repo
    git rev-parse --is-inside-work-tree &>/dev/null || return

    # quickest check for what branch we're on
    branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')

    # check if it's dirty (via github.com/sindresorhus/pure)
    dirty=$(git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ]&& echo -e "*")

    echo $WHITE" on "$BLUE$branch$RED$dirty
}

# Only show username/host if not default
function usernamehost() {
    if [ $USER != $default_username ]; then echo "${GREEN}$USER ${WHITE}-> "; fi #${GREEN}$HOSTNAME $WHITEin
}

# iTerm Tab and Title Customization and prompt customization
# http://sage.ucsc.edu/xtal/iterm_tab_customization.html

# Put the string " [bash]   hostname::/full/directory/path"
# in the title bar using the command sequence
# \[\e]2;[bash]   \h::\]$PWD\[\a\]

# Put the penultimate and current directory
# in the iterm tab
# \[\e]1;\]$(basename $(dirname $PWD))/\W\[\a\]

PS1="\n\[\e]2;$PWD\[\a\]\[\e]1;\]$(basename "$(dirname "$PWD")")/\W\[\a\]${BOLD}\$(usernamehost)\[$BLUE\]\w\$(git_info)\[$WHITE\]\n\$ \[$RESET\]"





