#!/bin/bash

#Create new directory and cd into it
function md()
{
mkdir -p "$@" && cd "$@"
}

#Go to up a level in folder structure
function up()
{
LIMIT=$1
P=$PWD
for ((i=1; i<=LIMIT; i++))
do
	P=$P/..
done
cd $P
export MPWD=$P
}

#Go back after going up
function back()
{
LIMIT=$1
P=$MPWD
for ((i=1; i<=LIMIT; i++))
do
	P=${P%/..}
done
cd $P
export MPWD=$P
}

function lines()
{
git ls-files | xargs wc -l | awk -F ' +|\\.|/' '{ sumlines[$NF] += $2 } END { for (ext in sumlines) print ext, sumlines[ext] }'
}

function man() {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
}